### PR TITLE
fix: line ending with non latin gurmukhi numbers

### LINKED ISSUE #158: Line endings with non latin/gurmukhi numbers
**Describe the bug**
https://github.com/ShabadOS/gurmukhi-utils/blob/43bf3b085456c8b14cb523b65919732df56aee5a/lib/stripEndings.js#L12 doesn't include hindi unicode numbers

**Screenshots**
See images in https://github.com/ShabadOS/desktop/pull/578

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Adds hindi unicode numbers to `stripEndings`

### Tests for unexpected behavior
added 2 new tests and it passes

### Time spent on PR
20 minutes

### Linked issues
Fixes #158

### Reviewers
@Harjot1Singh @bhajneet @Sarabveer

### CODE REVIEW

File: lib/stripEndings.js [hunk 1]
```diff
@@ -10,7 +10,10 @@ const optionalEndingClass = getRegexClass( [ '(' ] )
 const brokenEndingClass = getRegexGroup( [ '()' ] )
 
 // All numbers in ASCII, Unicode
-const numbers = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ].map( i => i.toString() )
+const numbers = [
+  0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
+  '१', '२', '३', '४', '५', '६', '७', '८', '९', '०',
```
Comment (Harjot1Singh) [inline lib/stripEndings.js:15]: Don't do this here, better to do it in L17 as something like `numbers.map(toUnicode).map(toHindi)`, instead of duplicating

Comment (bhajneet) [reply lib/stripEndings.js]: Just sharing my thoughts: I still think it's shorter and easier to understand typed out explicitly, these numbers don't change, and they're basically constants in the unicode spec

Comment (Harjot1Singh) [reply lib/stripEndings.js]: Hmm. Maybe you're right. I still suggested using the `toHindi` function, because we know that's correct, and I cannot read Hindi (or indeed any other languages we may add), and so cannot personally proof them.
